---
language: python
python: "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install -r requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: lCTGQgxNeOCKPVqEVMOGMlKYOA4nslJbt+tOxczeIj/2GT34Pfp4lPwFo67XReswykC/xIz5a8rJPzhRdXbgZgAxHWJUKNhf8LqRiMB0YJ+BdM1jpaK4ai+U7efg96ic12OPAhswavo3oji1evJdgPuVVu1ZBSy+onmsp2lUAOgiYCJZt6CuOvjHk+zY+kIaqBuP/8alNpIqMZBs52Yr8MrMHRu3rm+x87kqPTmYXjE6hpaOc9RwafHoCauPb5pLu1CZqF2YscjzVzk117clsikWjUBjQIKXNq98cZu24RwUg7ukay4A79E8FMnGeiVko1H0ImQaYdbCCkEpkAURqqhhPj5eX3P5an1v7rweU+DLGiOSbH9+J5RtN/AUW0mtB4NxJjB+3EykX3GTUwMv4xQYHVKsuMMXTIo1KO5jWfQqprPIV6VrtzKU/ayNu5rQZZWAuIePebEGAEG8m53sjaySGyhAQeBYkXooduwz/FhU5ffODNkaCBFcYfTXycC2sWMWo5urduRx5koYq8N/t1RGJW7zDxdjSQfJqgHf2YgwrdR79RRJy/LZNPwsqoZsxJRP3utxqz0pfEL1UYAhxQGFu1Mm9S2sF916qf/S2jwGwqtasFdhVOWh1KvJ3RWa0PVVtdWdoejSJP610C52T26OnZgF2x0Ru7r3GzRTVHU=
